config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get 'home/about' => 'homes#about', as: 'about'

  resources :books, only: [:index, :create, :show, :edit, :update, :destroy] do
    resources :book_comments, only: [:create, :destroy]

    resource :favorites, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  get '/search' => 'searches#search'
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  # class_nameを使用することで、実際はUserテーブルの所を:follower, :followedという仮想テーブルで扱ってもらう
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!
  def create
    user = User.find(params[:user_id])
    current_user.follow(user)
    redirect_to request.referer
  end

  def destroy
    user = User.find(params[:user_id])
    current_user.unfollow(user)
    redirect_to request.referer
  end

  def followings
    user = User.find(params[:user_id])
    @users = user.following_user
  end

  def followers
    user = User.find(params[:user_id])
    @users = user.follower_user
  end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_btn.html.erb
<% if current_user != user %> <!-- ログイン中のユーザーと一覧のユーザーが違う場合にのみ、ボタンを表示 -->
  <% if current_user.following?(user) %>
    <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class: "btn btn-info" %>
  <% else %>
    <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-success" %>
  <% end %>
<% end %>

app/views/relationships/_link.html.erb
<% if current_user != user %> <!-- ログイン中のユーザーと一覧のユーザーが違う場合にのみ、リンクを表示 -->
  <% if current_user.following?(user) %>
    <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
  <% else %>
    <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
  <% end %>
<% end %>

app/views/relationships/followers.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row d-flex flex-column'>
    <h2>Follower Users</h2>
    <% if @users.exists? %>
      <%= render '/users/index', users: @users %>
    <% else %>
      <p>ユーザーはいません</p>
    <% end %>
  </div>
</div>

app/views/relationships/followings.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row d-flex flex-column'>
    <h2>Follow Users</h2>
    <% if @users.exists? %>
      <%= render '/users/index', users: @users %>
    <% else %>
      <p>ユーザーはいません</p>
    <% end %>
  </div>
</div>