config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get 'home/about' => 'homes#about', as: 'about'

  resources :books, only: [:index, :create, :show, :edit, :update, :destroy] do
    resources :book_comments, only: [:create, :destroy]

    resource :favorites, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  get '/search' => 'searches#search'
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy


  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def self.search_for(content, method)
    if method == 'perfect'
      Book.where(title: content)
    elsif method == 'forward' # 前方一致
      Book.where('title LIKE ?', content+'%')
    elsif method == 'backward'
      Book.where('title LIKE ?', '%'+content)
    else
      Book.where('title LIKE ?', '%'+content+'%')
    end
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
    @book_comment = BookComment.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: 'You have created book successfully.'
    else
      @user = current_user
      @books = Book.all
      binding.pry
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
    @newbook = Book.new
    @user = @book.user
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render 'edit'
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: 'You have updated book successfully.'
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<h2 class="mt-3">New book</h2>
<%= form_with model: book, local:true do |f| %>
<div class="form-group">
  <label for="book_title">Title</label> <br />
  <%= f.text_field :title %>
</div>

<div class="form-group">
  <label for="book_opinion">Opinion</label> <br />
  <%= f.text_area :body %>
</div>

<div class="form-group">
  <%= f.submit "Create Book", class: "btn btn-success" %>
</div>
<% end %>

app/views/books/_errors.html.erb
<h3>
<% if book.errors.any? %>
  <%= book.errors.count %>errors prohibited this obj from being saved:
</h3>
<ul>
  <% book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
</ul>
<% end %>

app/views/books/_index.html.erb
<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
    <tr>
      <td>
        <%= link_to user_path(book.user_id) do %>
          <%= image_tag book.user.get_profile_image(50, 50) %><br />
        <% end %>
      </td>
      <td>
        <%= link_to book.title, book_path(book.id) %>
      </td>
      <td>
        <%= book.body %>
      </td>
      <% if book.favorited_by?(current_user) %>
      <td>
        <%= link_to book_favorites_path(book), class:"text-danger", method: :delete do %>
          <i class="fas fa-heart"></i>
          <%= book.favorites.count %>
        <% end %>
      </td>
      <% else %>
      <td>
        <%= link_to book_favorites_path(book), method: :post do %>
          <i class="fas fa-heart" aria-hidden="true"></i>
          <%= book.favorites.count %>
        <% end %>
      </td>
      <% end %>
      <td>
        コメント数：<%= book.book_comments.count %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <%= render 'errors', book: @book %>
      <%= form_with model: @book, local:true do |f| %>
      <div class="form-group">
        <label for="book_title">Title</label> <br />
        <%= f.text_field :title %>
      </div>

      <div class="form-group">
        <label for="book_opinion">Opinion</label> <br />
        <%= f.text_area :body %>
      </div>

      <div class="form-group">
        <%= f.submit "Update Book", class: "btn btn-success" %>
      </div>
      <% end %>

      <%= link_to "Show", book_path(@book) %>
      |
      <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <div id="error_explanation">
    <%= render 'errors', book: @book %>
  </div>
    <div class="row">
      <div class="col-md-3">
        <%= render 'users/info', user: @user %>
        <%= render 'book', book: @book %>
      </div>

      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <%= render 'index', books: @books %>
      </div>
    </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/info', user: @user %>
      <%= render 'books/book', book: @newbook %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@book.user) do %>
                <%= image_tag @book.user.get_profile_image(50,50) %><br />
                <%= @user.name %>
              <% end %>
            </td>
            <td>
              <%= link_to book_path(@book) do %>
                <%= @book.title %>
              <% end %>
            </td>
            <td>
              <%= @book.body %>
            </td>
            <% if @book.favorited_by?(current_user) %>
            <td>
              <%= link_to book_favorites_path(@book), class:"text-danger", method: :delete do %>
                <i class="fas fa-heart"></i>
                <%= @book.favorites.count %>
              <% end %>
            </td>
            <% else %>
            <td>
              <%= link_to book_favorites_path(@book), method: :post do %>
                <i class="fas fa-heart" aria-hidden="true"></i>
                <%= @book.favorites.count %>
              <% end %>
            </td>
            <% end %>
            <td>
              コメント数：<%= @book.book_comments.count %>
            </td>
            <% if @book.user_id == current_user.id %>
              <td>
                <%= link_to "Edit", edit_book_path(@book), class: "btn btn-sm btn-success edit_book_38390" %>
              </td>
              <td>
                <%= link_to "Destroy", book_path(@book), method: :delete, class: "btn btn-sm btn-danger destroy_book_38390", "data-confirm" => "本当に消しますか？" %>
              </td>
            <% end %>
          </tr>
        </tbody>
      </table>
      <table>
        <% @book.book_comments.each do |book_comment| %>
        <tr>
          <td>
            <%= image_tag book_comment.user.get_profile_image(50, 50) %><br />
            <%= link_to book_comment.user.name, user_path(book_comment.user.id) %>
          </td>
          <td>
            <%= book_comment.comment %>
            <% if book_comment.user == current_user %>
              <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, class:"btn btn-danger" %>
            <% end %>
          </td>
        </tr>
        <% end %>
      </table>
      <div>
        <%= form_with model: [@book, @book_comment] do |f| %>
          <div id="error_explanation">
            <%= render 'layouts/errors', obj: @comment %>
          </div>
          <%= f.text_area :comment, rows: '5' %> <br />
          <%= f.submit "送信" %>
        <% end %>
      </div>
    </div>
  </div>
</div>